### ISSUE TITLE
Table poor <th> handling

### ISSUE THREAD

**Issue by HugoHeneault** [PANmedia/raptor-editor#137] opened 2014-01-09 10:01 UTC
Hello, 

I'm trying to use this code
`````
<style>
	tr td
	{
		background: orange;
	}

        tr th
        {
		background: red;
	}
		
	.tr_spacer td, .tr_spacer th
	{
		background: white;
	}
</style>


<table width="100%"> 
	<thead> 
		<tr> 
			<th rowspan="2"> 
				<h3> 
					A title
				</h3> 
				<p> 
					Some content
				</p> 
			</th> 
			<th class="th_empty"></th> 
			<th class="th_empty"> </th> 
		</tr> 
		<tr> 
			<th> 
			Col 2
			</th> 
			<th> 
			Col 3
			</th> 
		</tr> 
	</thead> 
	<tbody> 
		<tr> 
			<th> 
			Row 1
			</th> 
			<td> 
				Data
			</td> 
			<td> 
				Data
			</td> 
		</tr> 
		<tr class="tr_spacer"> 
			<td></td> 
			<td></td> 
			<td></td> 
		</tr> 
		<tr> 
			<th> 
				Row 2
			</th> 
			<td> 
				Data
			</td> 
			<td> 
				Data
			</td> 
		</tr> 
	</tbody> 
</table> 
````

and Raptor is not able to delete a column and it doesn't delete the current row when asked.

My table structure is (sorry but markdown doesn't want to create this table, too)
th | th | th 
th | td | td 
th | td | td 

so I was expecting that creating a new row will add 
`<tr><th></th><td></td><td></td>` and not 
`<tr><td></td><td></td><td></td>`

**Comment by deeknow** [comment] 2015-11-21 07:07
Hi @HugoHeneault. I appreciate this issue was logged a long time ago but though't I'd post here about the behaviour for future reference before the issue is closed off.

At present as far as I can see Raptor-Editor does not support inserting a THEAD section or TH elements. Raptor uses a dependency lib GoogTable.js which inserts TR parents and TD children when adding new rows or columns. Users are free of course to edit the HTML source using the source editor button and add their own THEAD section with TR/TH child elements, I've tested that myself and when switching out of source mode the editor leaves the THEAD elements alone, does not alter them but you can of course then edit the TH elements contents.

Regarding your query about deleting columns, I've tested that also and it is possible to delete a column as long as you focus the cursor in one of the rows in the TBODY.

If inserting a THEAD is a desirable feature we can add it in future.

**Comment by deeknow** [comment] 2015-12-06 00:42
closing ticket

**Closed by deeknow** 2015-12-06 00:42 UTC
Labels: enhancement, question
