### ISSUE TITLE
Table resize controls shows hover dialogs

### ISSUE THREAD

**Issue by HugoHeneault** [PANmedia/raptor-editor#129] opened 2013-11-20 09:46 UTC
Create a table. Click inside it. Resizing controls appears. 
Then click on `Source code` or any dialog button. Resizing controls are shown hover the dialog.

**Comment by deeknow** [comment] 2015-11-21 07:16
@HugoHeneault just following up on this. Don't suppose you recall what browser or version this was on. Unable to reproduce so may be a legacy issue.

**Comment by deeknow** [comment] 2015-12-06 01:00
closing as unable to reproduce on any of the current browser releases

**Closed by deeknow** 2015-12-06 01:00 UTC
